
extends Reference

const UNIT_DEFINITIONS := {
	"Mummy": {
		FRO.MIN_SPAWN_RANGE: 2,
		FRO.SPAWN_WEIGHT: 100,
		FRO.HIT_POINTS: 1,
		FRO.MOVEMENT: 1,
		FRO.DAMAGE: 1,
	},
	"Ogre": {
		FRO.MIN_SPAWN_RANGE: 4,
		FRO.SPAWN_WEIGHT: 50,
		FRO.HIT_POINTS: 1,
		FRO.MOVEMENT: 1,
		FRO.DAMAGE: 1,
	},
}
